#!/bin/bash -l 
#SBATCH -p debug
#SBATCH -N 1
#SBATCH -t 00:01:00 
#SBATCH -J upc-HW3
#SBATCH -o upc-HW3.%j.out
#SBATCH -e upc-HW3.%j.err

# Parameters
P=4				# Number of UPC processes to run

# Run program
upcrun -n $P -shared-heap=1G ./kh
# aprun -n $P -N $P ./kh
